version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: encurtador_postgres
    restart: always
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: Password@Teste
      POSTGRES_DB: encurtador_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: encurtador_redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  postgres_data:
